### PR TITLE
Update electron lifetime to a value closer to data for upcoming MCP

### PR DESCRIPTION
**Pull request by gputnam**
I picked out 3.5ms -- does this seem reasonable?

### CODE REVIEW

**Comment by wesketchum** [comment]
Asking @marcodeltutto (and Alessandro? don't see him on here) to help coordinate common lifetimes. Probably @SFBayLaser or @cfarnese can comment as to a 'best' value for ICARUS right now.

**Comment by SFBayLaser** [comment]
Is this an SBN wide discussion to have? My impression was that we set it to "infinite" since a "real" lifetime could be accommodated in a different way? Sorry, my memory is a bit hazy on this

**Review by wesketchum — APPROVED** [review]
looks great to me.

**Review by SFBayLaser — APPROVED** [review]
I am concerned that the font used to type in the new lifetime could potentially impact all future experiments that use github. 

But as for the actual change I believe we have discussed this in enough detail at this point in time.

**Pull request merged**
