### PR TITLE
Remove redundant dependency from larcorealg

### PR DESCRIPTION
**Pull request by PetrilloAtWork**
`lardataalg` is currently the highest depedency, and it should suffice.

### CODE REVIEW

**Comment by SFBayLaser** [comment]
The correct dependency I am told is larsoftobj which will insure that gallery gets set up if you do a "setup icarusalg" as you might if running the event display. So I think this needs to be rejected. However, one can successfully argue otherwise...

**Comment by PetrilloAtWork** [comment]
We do not want gallery to be set up in MRB with LArSoft, which is the reason I skipped `larsoftobj` and went one step up.

**Comment by SFBayLaser** [comment]
Well, if I am using TITUS I DO want gallery set up with an icarusalg setup... suggestion?

**Comment by PetrilloAtWork** [comment]
No :frowning_face: 
The general approach I use for _gallery_-based programs is a _gallery_-specific setup script (like the one we distribute in `icarusalg`).

**Comment by wesketchum** [comment]
@SFBayLaser and @PetrilloAtWork : is this obsolete/already taken care of now? If so, let's close this out.

**Comment by SFBayLaser** [comment]
I believe this issue has been dealt with...

**Pull request closed without merging**
