### PR TITLE
Update detector geometry (icarus_v4) [1/2]

### PR DESCRIPTION
**Pull request by PetrilloAtWork**
This solves issue #53.
This is the main part of a multi-repository pull request. See also: SBNSoftware/icaruscode#404.

I have performed compilation and unit tests with `icarusalg` and `icaruscode` checked out.
**Please run the integration tests before merging!**

### CODE REVIEW

**Comment by mmrosenberg** [comment]
trigger build SBNSoftware/icaruscode#404

**Comment by SFBayLaser** [comment]
Looking at the CI test failures here... and, again, puzzled. It seems most of the failures are memory but, interestingly, I think it is because the memory usage is too low, provided my interpretation of `Problem: Error in data production *** Scaled cpu usage 170.1214232 not in 950.0:1400.0 range *** Memory usage 406428.0 not in 5900000.0:6800000.0 range` is correct. I assume the latter number is the mean and allowed variance expected for the job? So there is a substantial decrease in memory. Is that true only for this PR? If so, is this expected with the changes in geometry?

**Comment by SFBayLaser** [comment]
I understand the failure is actually that the test job cannot find the right geometry version. Perhaps Gianluca can look at this?

**Comment by PetrilloAtWork** [comment]
> the failure is actually that the test job cannot find the right geometry version

More precisely, they find the requested geometry, and they see it's not the same as the one used in the input file.
And they do not approve.

**Pull request merged**
