### PR TITLE
Update ICARUS E-field in active volume to 493.8 V/cm.

### PR DESCRIPTION
**Pull request by brucehoward-physics**
This is believed to be more in line with current understanding, though might not be the final change.

### CODE REVIEW

**Review by PetrilloAtWork — DISMISSED** [review]
Please add a comment (DocDB reference?) about where the new number is from.

Code-wise this is fine. The broader question is how do we want to deal with a value that will change with time. I don't know if the calibration group has decided on a strategy.

**Review by PetrilloAtWork — CHANGES_REQUESTED** [review]
Please add a statement in comment (DocDB reference?) about where the new number is from.

Code-wise this request is fine. The broader question is how we want to deal with a value that will change with time. I don't know if the calibration group has decided on a strategy which, needless to say, will deeply impact the usage patterns of simulated samples.

**Comment by brucehoward-physics** [comment]
Thanks for the comments. I've requested the author of the supporting document upload it to doc-db and will make a follow-up commit with the comment when that's uploaded.

Indeed, the second bit is something that needs to be worked out.

**Comment by jzennamo** [comment]
One other question is does this impact the space-charge maps? Will we need to update them to correspond to this new base electric field?

**Review by PetrilloAtWork — APPROVED** [review]

**Comment by brucehoward-physics** [comment]
Added comment on the E-field calculation. The Vp value in the calculation comes from @mrmooney who had access to files with the voltages. I don't know if he got the assumed value from an averaging?

Also, @jzennamo -- I think @mrmooney should really be the one to answer your question as he's the expert of the SCE maps.

**Comment by jzennamo** [comment]
@mrmooney has confirmed that this change shouldn't invalidate the SCE maps that are currently being used

**Review by cfarnese — APPROVED** [review]

**Review by mrmooney — APPROVED** [review]
Looks fine to me

**Comment by SFBayLaser** [comment]
On the assumption that four reviewers is overkill I will drop Filippo and go with the three approvals so I can start the release process...

**Comment by SFBayLaser** [comment]
Actually, in reviewing the conflict this raised the question in my mind that the proposed change is for the main drift field, the next two parameters are the interplane values. I believe it was Leon who supplied those numbers based on his 1D field response model which was based on different bias voltages (from previous running) than what we run now... Should we try to fix all?

**Comment by brucehoward-physics** [comment]
I don't have super precise values of the bias voltages or their variations, but my understanding is the nominal values are -250, -30, and +250 V (see ECL 35506 for example). ECL 31796 is somewhat old but does specify values close to this nominal. We probably would need to ask the experts how much variation they are seeing or if there is some offset.

Now, I think @PetrilloAtWork said the gaps between planes were 3 mm, and then taking .220 kV / 0.3 cm = 0.733 kV/cm, and .280 kV / 0.3 cm = 0.933 kV/cm does return the values in the code. I had previously asked Gianluca about what these 2nd and 3rd values meant 😅 

But maybe these numbers are more precisely found in a more complicated way ideally?

**Comment by varanini** [comment]
Ok for me

⁣Ottieni BlueMail per Android ​

Il giorno 10 set 2021, 20:13, alle ore 20:13, Tracy Usher ***@***.***> ha scritto:

**Comment by SFBayLaser** [comment]
Thanks Bruce! Now that I remember things, Leon said the bias voltages he originally used were different from what we were used when we turned on but that the potential difference between the planes was the same. So it sounds like we are ok and I'll resolve the conflict and make the merge.

**Pull request merged**
