### PR TITLE
Switch on the alternative drift velocity calculation for ICARUS. (Resolves SBNSoftware/icaruscode#291)

### PR DESCRIPTION
**Pull request by brucehoward-physics**
Resolves SBNSoftware/icaruscode#291.

### CODE REVIEW

**Comment by jzennamo** [comment]
trigger build

**Comment by wesketchum** [comment]
Resolves SBNSoftware/icaruscode#291

**Comment by jzennamo** [comment]
@brucehoward-physics do we expect this to have any effect on the downstream physics simulation? Do you have any plots from before and after this change?

**Comment by brucehoward-physics** [comment]
I checked just that it changed the drift velocity printed out by `DetectorPropertiesStandard_test multitpc_detsim_icarus.fcl`. 

In principle changes to the drift velocity would change the downstream reco, for example by changing where the cathode is situated at T=0.

However, this is a fairly small change to our nominal drift velocity (before: `0.158092 cm/us`, after: `0.157565 cm/us`, which is a fraction of a percent) and so I don't know that I would expect to see much difference at this level.

**Comment by PetrilloAtWork** [comment]
I infer that the Slack thread referred in SBNSoftware/icaruscode#291 got to the conclusion that this is the way to go?

**Comment by brucehoward-physics** [comment]
I believe from said thread that @mrmooney was in favor (he originally communicated re the alternative model that was added), but I have added him as a reviewer in case he's had further thought or some qualm(s).

Of course anyone else who may have an opinion can (should) weigh in if desired!

**Review by PetrilloAtWork — COMMENTED** [review]
The change is technically ok, and I don't see any fundamental issue.
Given that a discussion has been taken place, which I was not part of, I defer the formal approval to the outcome of that discussion (the other reviewer, @mrmooney, was involved and should know that conclusion).

**Comment by SFBayLaser** [comment]
Be sure to ping Mike directly so he knows to approve!

Sent from my iPhone X

On Nov 22, 2021, at 12:43 PM, Gianluca Petrillo ***@***.***> wrote:

﻿

@PetrilloAtWork commented on this pull request.

The change is technically ok, and I don't see any fundamental issue.
Given that a discussion has been taken place, which I was not part of, I defer the formal approval to the outcome of that discussion (the other reviewer, @mrmooney<https://github.com/mrmooney>, was involved and should know that conclusion).

**Review by mrmooney — APPROVED** [review]
Yes, good to make this change. It more accurately represents our drift velocities at ICARUS, especially (1) including more appropriate temperature dependence at ICARUS E fields (< 1 kV/cm) and (2) better match to existing data at lower E fields (< 400 V/cm).  Impact at 500 V/cm may be small depending on the exact LAr temperature.

**Pull request merged**
