### PR TITLE
Updated geometry made available

### PR DESCRIPTION
**Pull request by PetrilloAtWork**

### CODE REVIEW

**Comment by wesketchum** [comment]
Sorry, don't know why this was labeled duplicate. Probably error on my part.

**Comment by wesketchum** [comment]
@PetrilloAtWork and @SFBayLaser: is this PR still outstanding, or is it otherwise obsolete? If the latter, can we close it out?

**Comment by PetrilloAtWork** [comment]
We have moved seven geometries further since that point.

**Comment by PetrilloAtWork** [comment]
That reads as: yes, please close this one (I let you enjoy the act).

**Pull request merged**
