### PR TITLE
Turn off InterPlane offset

### PR DESCRIPTION
**Pull request by gputnam**

### CODE REVIEW

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_65_01

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_64_01

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_64_01 SBNSoftware/sbncode@v09_64_01 SBNSoftware/sbnanaobj@v09_20_01 SBNSoftware/sbndaq_artdaq_core@v1_04_02of0 SBNSoftware/sbnobj@v09_15_02

**Review by brucehoward-physics — CHANGES_REQUESTED** [review]
I believe that at the moment we need it set `true` in the 1D simulation case (because of https://github.com/SBNSoftware/icaruscode/blob/develop/icaruscode/TPC/Simulation/DetSim/SimReadoutBoardICARUS_module.cc#L445). That would be `detsim_1d_icarus.fcl`.

Now... if we change the 1D sim case to remove the line doing this offset, then we would instead need the parameter true in the reco stage. Anyway, that can be addressed in a future PR if that line is changed. For now, we should just have an added line to the 1D detsim fcl probably, and thus a corresponding `icaruscode` PR.

@SFBayLaser is there anywhere else it's needed to be `true` at present?

**Comment by gputnam** [comment]
Following up on this -- I'm pretty sure the configuration change here means that the code Bruce linked to should also just be changed. We don't have interplane timing offsets in the detector configuration anymore. @SFBayLaser could you confirm?

**Comment by SFBayLaser** [comment]
I can't look today to reconfirm, but I think the fhicl files now on a feature branch are consistent from detector simulation through reconstruction for both 1D and 2D drift simulations. I will check again tomorrow when I can resurface from today's task list.

**Comment by mmrosenberg** [comment]
trigger build

**Comment by mmrosenberg** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_66_00

**Review by SFBayLaser — APPROVED** [review]
I believe this is ok, it might require some corresponding updates to fhicl files in icaruscode.

**Pull request merged**
